#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := trync-agent

#EXTRA_COMPONENT_DIRS := ./components/paho.mqtt.embedded-c/ 


include $(IDF_PATH)/make/project.mk
#COMPONENT_INCLUDES += /stuff/PROJECTS/TRYNC/Libs-embedded/paho.mqtt.embedded-c/MQTTPacket/src
#COMPONENT_INCLUDES += /stuff/PROJECTS/TRYNC/Libs-embedded/paho.mqtt.embedded-c/MQTTClient-C/src
#COMPONENT_INCLUDES += /stuff/PROJECTS/TRYNC/Libs-embedded/paho.mqtt.embedded-c/MQTTClient/src
#export COMPONENT_INCLUDES

#COMPONENT_ADD_LDFLAGS += -lpaho-embed-mqtt3c
#export COMPONENT_ADD_LDFLAGS

#COMPONENT_BUILD_DIR += /stuff/PROJECTS/TRYNC/Libs-embedded/paho.mqtt.embedded-c/build/output
#export COMPONENT_BUILD_DIR
